model_type: "value_model"

precision: bf16

# Not supported for this model
is_lora: false

backbone_variant: "paligemma"

# "gemma_2b" (default)
paligemma_variant: "gemma_2b"

# "gemma_50m" | "gemma_100m" | "gemma_150m" | "gemma_300m" | "gemma_2b"
critic_expert_variant: "gemma_100m"

# Categorical value head
num_bins: 201           # number of discretization bins
v_min: -1.0             # minimum value for atom support
v_max: 0.0              # maximum value for atom support
value_dropout: 0.0

action_dim: 32
action_horizon: 50
max_token_len: 200

action_expert_variant: "gemma_50m"
freeze_vision_encoder: false
train_expert_only: false
forward_mode: "vla"
max_language_len: 50
stop_gradient_to_vlm: false

model_path: "/path/to/checkpoint"
