defaults:
  - model/mlp_policy@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-0

runner:
  task_type: "offline"
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "d4rl_offline_mujoco"
    logger_backends: ["tensorboard"]

  max_epochs: 1000000
  max_steps: 1000000

  only_eval: false
  val_check_interval: 5000  # step interval for checkpoint/validation
  save_interval: 50000

  resume_dir: null
  save_dir: null
  ckpt_path: null

  log_interval: 1000
  local_update_steps: 500
  eval_interval: 5000
  eval_episodes: 10

algorithm:
  adv_type: null
  batch_size: 256
  actor_lr: 3.0e-4
  value_lr: 3.0e-4
  critic_lr: 3.0e-4
  hidden_dims: [256, 256]
  discount: 0.99
  tau: 0.005
  expectile: 0.7
  temperature: 3.0
  dropout_rate: null
  opt_decay_schedule: "cosine"

env:
  group_name: "EnvGroup"
  env_name: "halfcheetah-medium-expert-v2"

rollout:
  group_name: "RolloutGroup"
  pipeline_stage_num: 1

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  use_fsdp_wrap: false
  seed: 42
  offline_torch_compile: true

reward:
  use_reward_model: false

critic:
  use_critic_model: false
