defaults:
  - model/gr00t_16@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  hardware_ranks: [[0]]
  component_placement:
    actor: all

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "gr00t_16_sft_libero"
    logger_backends: ["tensorboard"] 

  max_epochs: 100000
  max_steps: -1
  val_check_interval: -1
  save_interval: 2000

data:
  train_data_paths: "/path/to/your/libero_spatial_dataset" 

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  num_gpus: 1
  micro_batch_size: 4
  global_batch_size: 4
  seed: 0
  enable_offload: False

  model:
    model_path: "/path/to/GR00T-N1.6-3B" 
    model_type: "gr00t_1_6_sft"
    precision: "bf16"
    action_dim: 128
    num_action_chunks: 1
    add_value_head: True
    denoising_steps: 1
    no_split_modules:
      - "Qwen3DecoderLayer"
      - "Siglip2EncoderLayer"
      - "FlowMatchingActionHeadForRLActionPrediction"
      - "TimestepEncoder"
      - "TimestepEmbedding"
      - "ValueHead"
      - "ExploreNoiseNet" 

  optim:
    # lr: 2.5e-5  
    lr: 1e-5
    value_lr: 1e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    # adam_eps: 1.0e-08  
    adam_eps: 1e-04
    # weight_decay: 1.0e-10  
    weight_decay: 0.01
    clip_grad: 1.0
    warmup_style: "cosine"  
    # lr_warmup_steps: 1000  
    lr_warmup_steps: 100
    total_training_steps: 3000

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "shard_grad_op"
    use_orig_params: True
    gradient_checkpointing: False
    transformer_layer_cls_to_wrap:
      - "Qwen3DecoderLayer"
      - "Siglip2EncoderLayer"
      - "Gr00tN1d6ActionHead"

    mixed_precision:
      param_dtype: "bf16"
      reduce_dtype: "fp32"
      buffer_dtype: "bf16"

reward:
  use_reward_model: False

critic:
  use_critic_model: False