version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - export UV_HTTP_TIMEOUT=120
      - python -m pip install -U uv
      - uv pip install .[embodied]
      - uv pip install .[agentic-sglang]
      - uv pip install .[agentic-vllm]
      - uv pip install -r requirements/docs/requirements.txt

sphinx:
  configuration: docs/source-en/conf.py
  fail_on_warning: true
