#!/usr/bin/env python3
"""Replay one collected joint-space PegInsertionSide-v1 LeRobot episode.

This validates the dataset generated by
``collect_maniskill_peg_lerobot_joint.py`` by:

1. loading one LeRobot episode,
2. resetting ManiSkill with the same seed used during collection,
3. replaying the saved 8D ``pd_joint_delta_pos`` actions, and
4. comparing replayed 9D Panda qpos state against dataset state.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np


def _bootstrap_repo_paths() -> Path:
    script_path = Path(__file__).resolve()
    rlinf_root = script_path.parents[2]
    repo_root = rlinf_root.parent
    for candidate in (rlinf_root, repo_root / "openpi-RLT" / "src"):
        candidate_str = str(candidate)
        if candidate.exists() and candidate_str not in sys.path:
            sys.path.insert(0, candidate_str)
    os.environ.setdefault("EMBODIED_PATH", str(script_path.parent))
    return rlinf_root


RLINF_ROOT = _bootstrap_repo_paths()

from rlinf.envs.maniskill.peg_insertion_side_variants import (  # noqa: E402
    PEG_INSERTION_SIDE_HARD_ENV_ID,
    register_rlinf_peg_insertion_side_variants,
)

ENV_ID = PEG_INSERTION_SIDE_HARD_ENV_ID
STATE_DIM = 9
ACTION_DIM = 8


def _missing_dep_error(package: str) -> RuntimeError:
    return RuntimeError(
        f"Missing runtime dependency '{package}'. Run this in the same server "
        "environment where you collected the ManiSkill dataset."
    )


def _to_numpy(value: Any) -> np.ndarray:
    if hasattr(value, "detach"):
        value = value.detach().cpu().numpy()
    arr = np.asarray(value)
    if arr.ndim > 0 and arr.shape[0] == 1:
        arr = arr[0]
    return arr


def _truthy_first(value: Any) -> bool:
    if value is None:
        return False
    arr = _to_numpy(value).reshape(-1)
    return bool(arr[0]) if arr.size else False


def _extract_state(raw_obs: dict[str, Any]) -> np.ndarray:
    qpos = _to_numpy(raw_obs["agent"]["qpos"]).astype(np.float32)
    if qpos.shape[0] < STATE_DIM:
        raise RuntimeError(f"Expected Panda qpos with at least {STATE_DIM} values, got {qpos.shape}")
    return qpos[:STATE_DIM].astype(np.float32)


def _state_error(label: str, replay_state: np.ndarray, dataset_state: np.ndarray) -> str:
    diff = replay_state - np.asarray(dataset_state, dtype=np.float32).reshape(-1)
    return (
        f"{label}: max_abs={float(np.max(np.abs(diff))):.6g} "
        f"mean_abs={float(np.mean(np.abs(diff))):.6g}"
    )


def _episode_seed_from_videos(dataset_path: Path, episode_index: int) -> int | None:
    video_dir = dataset_path.with_name(f"{dataset_path.name}_videos")
    if not video_dir.exists():
        return None
    pattern = f"episode_{episode_index:06d}_seed_*.mp4"
    matches = sorted(video_dir.glob(pattern))
    if not matches:
        return None
    match = re.search(r"_seed_(\d+)\.mp4$", matches[0].name)
    return int(match.group(1)) if match else None


def _episode_bounds(dataset: Any, episode_index: int) -> tuple[int, int]:
    if hasattr(dataset, "episode_data_index") and dataset.episode_data_index is not None:
        data_index = dataset.episode_data_index
        if episode_index < len(data_index["from"]):
            return (
                int(data_index["from"][episode_index].item()),
                int(data_index["to"][episode_index].item()),
            )

    indices = []
    for idx in range(len(dataset)):
        sample = dataset[idx]
        if int(_to_numpy(sample["episode_index"]).reshape(-1)[0]) == episode_index:
            indices.append(idx)
    if not indices:
        raise RuntimeError(f"Episode {episode_index} not found in dataset")
    return min(indices), max(indices) + 1


def _load_episode(dataset_path: Path, episode_index: int) -> list[dict[str, Any]]:
    try:
        from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
    except ImportError as exc:
        raise _missing_dep_error("lerobot") from exc

    dataset = LeRobotDataset(str(dataset_path), download_videos=False)
    start, end = _episode_bounds(dataset, episode_index)
    rows = [dataset[idx] for idx in range(start, end)]
    if not rows:
        raise RuntimeError(f"Episode {episode_index} is empty")
    return rows


def _build_env(args: argparse.Namespace):
    try:
        import gymnasium as gym
    except ImportError as exc:
        raise _missing_dep_error("gymnasium") from exc
    try:
        import mani_skill.envs  # noqa: F401
    except ImportError as exc:
        raise _missing_dep_error("mani_skill") from exc

    register_rlinf_peg_insertion_side_variants()
    sim_freq = max(args.sim_freq, args.control_freq * 8)
    sim_freq -= sim_freq % args.control_freq
    return gym.make(
        ENV_ID,
        obs_mode="rgb",
        control_mode="pd_joint_delta_pos",
        reward_mode=args.reward_mode,
        render_mode="rgb_array",
        sim_backend=args.sim_backend,
        sim_config={"sim_freq": sim_freq, "control_freq": args.control_freq},
        sensor_configs={
            "shader_pack": args.shader_pack,
            "width": args.image_width,
            "height": args.image_height,
        },
        max_episode_steps=args.max_episode_steps,
    )


def _summarize_actions(rows: list[dict[str, Any]]) -> dict[str, Any]:
    actions = np.asarray([_to_numpy(row["actions"]).reshape(-1) for row in rows], dtype=np.float32)
    if actions.ndim != 2 or actions.shape[1] != ACTION_DIM:
        raise RuntimeError(f"Expected episode actions with shape [T, {ACTION_DIM}], got {actions.shape}")
    return {
        "action_dim": int(actions.shape[1]),
        "min": actions.min(axis=0).round(6).tolist(),
        "max": actions.max(axis=0).round(6).tolist(),
        "first": actions[0].round(6).tolist(),
    }


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay one collected widened PegInsertionSide-v1 joint LeRobot episode."
    )
    parser.add_argument("--dataset-path", required=True)
    parser.add_argument("--episode-index", type=int, default=0)
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="ManiSkill reset seed. Defaults to seed parsed from <dataset>_videos.",
    )
    parser.add_argument("--max-steps", type=int, default=500)
    parser.add_argument("--log-every", type=int, default=10)
    parser.add_argument("--image-width", type=int, default=384)
    parser.add_argument("--image-height", type=int, default=384)
    parser.add_argument("--control-freq", type=int, default=10)
    parser.add_argument("--sim-freq", type=int, default=100)
    parser.add_argument("--sim-backend", default="physx_cpu")
    parser.add_argument("--shader-pack", default="default")
    parser.add_argument("--reward-mode", default="sparse")
    parser.add_argument("--max-episode-steps", type=int, default=500)
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    dataset_path = Path(args.dataset_path).expanduser()
    seed = args.seed
    if seed is None:
        seed = _episode_seed_from_videos(dataset_path, args.episode_index)
    if seed is None:
        raise RuntimeError(
            "Could not infer collection seed. Pass --seed explicitly, or keep "
            f"{dataset_path.with_name(dataset_path.name + '_videos')} with seed in filenames."
        )

    rows = _load_episode(dataset_path, args.episode_index)
    print(
        json.dumps(
            {
                "dataset_path": str(dataset_path),
                "episode_index": args.episode_index,
                "seed": seed,
                "episode_frames": len(rows),
                "control_mode": "pd_joint_delta_pos",
            },
            indent=2,
        )
    )
    print(json.dumps({"action_summary": _summarize_actions(rows)}, indent=2))

    env = _build_env(args)
    try:
        raw_obs, _ = env.reset(seed=seed)
        replay_state = _extract_state(raw_obs)
        print(_state_error("step0_state_vs_dataset", replay_state, rows[0]["state"]))

        first_success_step = None
        last_info: dict[str, Any] = {}
        steps_run = min(args.max_steps, len(rows))
        stopped_reason = "max_steps"
        for step_idx in range(steps_run):
            action = _to_numpy(rows[step_idx]["actions"]).astype(np.float32).reshape(-1)
            if action.shape[0] != ACTION_DIM:
                raise RuntimeError(f"Expected {ACTION_DIM}D action, got {action.shape}")

            raw_obs, reward, terminated, truncated, info = env.step(action)
            last_info = info
            replay_state = _extract_state(raw_obs)

            if first_success_step is None and _truthy_first(info.get("success")):
                first_success_step = step_idx + 1

            should_log = (
                step_idx == 0
                or (step_idx + 1) % args.log_every == 0
                or _truthy_first(info.get("success"))
            )
            if should_log:
                target_idx = min(step_idx + 1, len(rows) - 1)
                print(
                    f"step={step_idx + 1} "
                    f"reward={_to_numpy(reward).reshape(-1).tolist()} "
                    f"terminated={_to_numpy(terminated).reshape(-1).tolist()} "
                    f"truncated={_to_numpy(truncated).reshape(-1).tolist()} "
                    f"success={_to_numpy(info.get('success', False)).reshape(-1).tolist()} "
                    + _state_error(
                        f"state_vs_dataset_frame_{target_idx}",
                        replay_state,
                        rows[target_idx]["state"],
                    )
                )

            if _truthy_first(terminated) or _truthy_first(truncated):
                stopped_reason = "terminated_or_truncated"
                break
        else:
            if len(rows) <= args.max_steps:
                stopped_reason = "dataset_end"

        print(f"steps_run={step_idx + 1 if rows else 0}")
        print(f"stopped_reason={stopped_reason}")
        print(f"first_success_step={first_success_step}")
        print(f"final_success={_to_numpy(last_info.get('success', False)).reshape(-1).tolist()}")
    finally:
        env.close()


if __name__ == "__main__":
    main()
